#ifndef __LAYER_TAG_DEFINE_H__
#define __LAYER_TAG_DEFINE_H__

enum LayerTag
{
	LAYER_TAG_GAME_START = 2673,	// 随机起的数字，避免重复
	LAYER_TAG_BLUETOOTH_BLUETOOTH,
	LAYER_TAG_BLUETOOTH_MAIN,
	LAYER_TAG_BLUETOOTH_VICTORY,

	LAYER_TAG_BLUETOOTH_SERVER,
	LAYER_TAG_BLUETOOTH_CLIENT
};

#endif // __LAYER_TAG_DEFINE_H__
